repos:
-   repo: local
    hooks:
    -   id: cfn-guard
        name: AWS CloudFormation Guard
        description: Validate code against your Guard rules
        entry: cfn-guard validate -r ../cfn-guard -d templates
        language: rust
        additional_dependencies:
          - cli:cfn-guard
        files: \.(json|yaml|yml|template\.json|template)$
        pass_filenames: false