AWSTemplateFormatVersion: '2010-09-09'
Description: 'Deploying repeatable, secure, and compliant Amazon EKS clusters' 
Parameters:

# Portfolio Provider Name
  PortfolioProviderName:
    Description:    Please specify the Portfolio Provider Name.
    Type:           String
    Default:        "IT Provider"

# Portfolio Description
  PortfolioDescription:
    Description:    Please specify the Portfolio Description.
    Type:           String
    Default:        "Service Catalog Portfolio for Business Unit (BU)"

# Portfolio Display Name
  PortfolioDisplayName:
    Description:    Please specify the Portfolio Description. Must satisfy regular expression pattern, (^[a-zA-Z0-9_\-]*)
    Type:           String
    Default:        "EKS Portfolio"


Resources:

  ServiceCatalogPortfolio:
    Type: "AWS::ServiceCatalog::Portfolio"
    Properties:
      ProviderName: !Ref 'PortfolioProviderName'
      Description: !Ref 'PortfolioDescription'
      DisplayName: !Ref 'PortfolioDisplayName'
  ServiceCatalogPortfolioPrincipalAssociation:
    Type: AWS::ServiceCatalog::PortfolioPrincipalAssociation
    Properties:
      PortfolioId: !Ref ServiceCatalogPortfolio
      PrincipalARN: !Sub 'arn:aws:iam:${AWS::Region}:${AWS::AccountId}:role/WSParticipantRole'
      PrincipalType: IAM

Outputs:

  ServiceCatalogPortfolio:
    Value:    !Ref 'ServiceCatalogPortfolio'
    Export:
      Name:   !Sub '${AWS::StackName}-ServiceCatalogPortfolio'

  ServiceCatalogPortfolioName:
    Value:    !GetAtt 'ServiceCatalogPortfolio.PortfolioName'
    Export:
      Name:   !Sub '${AWS::StackName}-ServiceCatalogPortfolioName'
