AWSTemplateFormatVersion: '2010-09-09'
Description: 'Deploying Amazon EKS managed nodegroup'
Parameters:
  ServiceCatalogPortfolioStackName:
    Description:    Please specify the Service Catalog Portfolio Stack Name.
    Type:           String
    Default:        ""
  ProvisioningArtifactNameParameter:
    Description:    Please specify ServiceCatalog Product Artifact Name.
    Type:           String
    Default:        "EKS Service Catalog Product"
  ProvisioningArtifactDescriptionParameter:
    Description:    Please specify ServiceCatalog Product Artifact Description.
    Type:           String
    Default:        "EKS Service Catalog Product"
Resources:
  ServiceCatalogCloudFormationProduct:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties: 
      Description: 'EKS Service Catalog Product'
      Name: 'EKS Managed Nodegroup Product'
      Owner: 'Workshop Studio'
      ProvisioningArtifactParameters: 
        - Name: !Sub '${ProvisioningArtifactNameParameter}'
          Description: !Sub '${ProvisioningArtifactDescriptionParameter}'
          Info:
            "LoadTemplateFromURL": "https://s3.amazonaws.com/ee-assets-prod-us-east-1/modules/ca84f92e9e3946dc8ab910b823799d41/v3/eksnodegroup.yaml"
  ServiceCatalogPortfolioProductAssociation:
    Type: "AWS::ServiceCatalog::PortfolioProductAssociation"
    DependsOn: 
      - ServiceCatalogCloudFormationProduct
    Properties:
      PortfolioId:
        Fn::ImportValue: !Sub '${ServiceCatalogPortfolioStackName}-ServiceCatalogPortfolio'
      ProductId: !Ref 'ServiceCatalogCloudFormationProduct'
  ServiceCatalogLaunchRole:
    Type: AWS::ServiceCatalog::LaunchRoleConstraint
    Properties: 
      LocalRoleName: WSParticipantRole
      PortfolioId:
        Fn::ImportValue: !Sub '${ServiceCatalogPortfolioStackName}-ServiceCatalogPortfolio'
      ProductId: !Ref 'ServiceCatalogCloudFormationProduct'
    DependsOn:
      - ServiceCatalogPortfolioProductAssociation
