AWSTemplateFormatVersion: "2010-09-09"
Description: Service Catalog Product - Nginx Helm Chart
Parameters:
  HelmChartUrl:
    Type: String
    Default: ''
    Description: Enter the S3 URL for helm-nginx.yaml
Resources:
  SCHelmNginx:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties: 
      Description: Nginx Helm Chart
      Distributor: reInforce 2022
      Name: Nginx
      Owner: Workshop Studio
      ProvisioningArtifactParameters: 
        - Description: Nginx default from helm chart
          Info: 
            LoadTemplateFromURL: !Ref HelmChartUrl
          Name: v1
      Tags: 
        - Key: Environment
          Value: Workshop Studio
Outputs:
   SCHelmNginx:
    Description: Service Catalog Product Nginx
    Value: !Ref SCHelmNginx
    Export:
      Name: 
        'Fn::Sub': '${AWS::StackName}-SCHelmNginx'