AWSTemplateFormatVersion: "2010-09-09"
Description: Service Catalog Product - Simple EKS
Parameters:
  CodeStarArn:
    Type: String
    Description: The CodeStar ARN, which is the connection between AWS Service Catalog and the external repository.
  Repository:
    Type: String
    Description: The specific repository where the product’s artifact-to-be-synced resides, formatted as "Account/Repo."
  Branch:
    Type: String
    Description: The specific branch where the artifact resides. 
  ArtifactPath:
    Type: String
    Description: The absolute path where the artifact resides within the repo and branch, formatted as "folder/file.json." 
Resources:
  ProductSimpleEKS:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties: 
      Description: Simple EKS cluster
      Distributor: Workshop Studio
      Name: Simple EKS cluster
      Owner: Workshop Studio
      ProductType: CLOUD_FORMATION_TEMPLATE
      SourceConnection:
        ConnectionParameters:
          CodeStar:
            ArtifactPath: !Ref ArtifactPath
            Branch: !Ref Branch
            ConnectionArn: !Ref CodeStarArn
            Repository: !Ref Repository
        Type: CODESTAR
      Tags: 
        - Key: Environment
          Value: Workshop Studio
Outputs:
   ProductPA:
    Description: Service Catalog Product - Simple EKS
    Value: !Ref ProductSimpleEKS
    Export:
      Name: 
        'Fn::Sub': '${AWS::StackName}-ProductPA'